name: App Nuxt - E2E tests
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    paths:
      - 'apps/hello-carbon-nuxt/**'
      - '.github/workflows/app-nuxt-e2e.yml'
      - 'package-lock.json'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # firefox is not working for auth - https://github.com/cypress-io/cypress/issues/18217
        browser: [ chrome, edge ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Start containers
        working-directory: apps/hello-carbon-nuxt/local-dev/
        run: |
          docker compose -f "compose.yml" up -d
          docker compose logs --follow ibmid &
          sleep 45

      - name: Start mock marvel server
        uses: mockoon/cli-action@v3.0.0
        with:
          version: "latest"
          data-file: "./apps/hello-carbon-nuxt/local-dev/mock/mock-api.json"
          port: 4513

      - name: Test with sample env
        working-directory: apps/hello-carbon-nuxt
        run: cp .env.example .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          PORT: 4507
        with:
          build: npm run build --workspace=apps/hello-carbon-nuxt
          start: npm run preview --workspace=apps/hello-carbon-nuxt
          browser: ${{ matrix.browser }}
          project: apps/hello-carbon-nuxt
