name: App Vue3 - E2E tests
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    paths:
      - 'apps/hello-carbon-vue3/**'
      - 'app-vue3-e2e.yml'
      - 'package-lock.json'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run dev:build --workspace=apps/hello-carbon-vue3
          start: npm run dev:preview --workspace=apps/hello-carbon-vue3
          browser: ${{ matrix.browser }}
          project: apps/hello-carbon-vue3
